### PR TITLE
Fix example configs in README.

### PR DESCRIPTION
**Pull request by pschultz**

### CODE REVIEW

**Comment by mvisonneau** [comment]
👋 thanks for your contribution @pschultz 

I am not sure this is correct though, the chart expects the `config` as the entrypoint 🤔 ?

**Comment by pschultz** [comment]
> I am not sure this is correct though, the chart expects the config as the entrypoint.

I realized that shortly after I submitted the PR and amended the commit to undo that change.

**Comment by pschultz** [comment]
Looks like the commit hasn't been merged. Did you close the PR by accident?

**Comment by mvisonneau** [comment]
my bad indeed, it was a mistake 🙇

**Pull request merged**
