### PR TITLE
Add vars for project and ref on example Grafana dashboard

### PR DESCRIPTION
**Pull request by jeff-cook**
By having variables for project and ref in the dashboard it will allow more fine-grained viewing while collecting all or more refs.

### CODE REVIEW

**Comment by jeff-cook** [comment]
@mvisonneau any recommendations?

**Comment by mvisonneau** [comment]
love it, thanks @jeff-cook! happy to merge it

**Comment by mvisonneau** [comment]
thanks @jeff-cook ! 🙇

**Comment by jeff-cook** [comment]
@mvisonneau glad to help.

**Pull request merged**
