### PR TITLE
Add failure_reason to job status

### PR DESCRIPTION
**Pull request by robbydyer**
This adds the job failure reason to the job status data.

### CODE REVIEW

**Comment by aaronborden-rivian** [comment]
@robbydyer thanks for doing this, can you include documentation? @mvisonneau any chance you can take a look? We'd be interested int getting this merged.

**Comment by ilietrasca** [comment]
Any updates regarding this ? @aaronborden-rivian

**Comment by confar** [comment]
@mvisonneau hi, are there any updates? 

planning to use this for evaluating the percentage of tests that are failing due to infrastructure reasons and establishing SLA on that. 

this mr would be really helpful

**Comment by mvisonneau** [comment]
This should be included in the next release now that #718 is merged!

**Pull request closed without merging**
